version: '3'
services:
  splunk:
    hostname: splunkenterprise
    #image: splunk/splunk:latest
    build:
      context: ./splunk
      dockerfile: Dockerfile
    container_name: splunk
    environment:
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes
      - SPLUNK_USERNAME=admin
      - SPLUNK_PASSWORD=password
    restart: always
    volumes:
      - opt_splunk_etc:/opt/splunk/etc
      - opt_splunk_var:/opt/splunk/var
      - sqli-labs-apache2:/var/log/apache2
      - sqli-labs-mysql:/var/log/mysql
    ports:
      - "8000:8000"
      #- "9997:9997"
      #- "8088:8088"
      #- "1514:1514"
      #- "514:514/udp"
    restart: always
  sqli-labs:
    build:
      context: ./sqli-labs
      dockerfile: Dockerfile
    container_name: sqli-labs
    ports:
      - "80:80"
    volumes:
      - sqli-labs-apache2:/var/log/apache2
      - sqli-labs-mysql:/var/log/mysql 
  sqlmap:
    build:
      context: ./sqlmap
      dockerfile: Dockerfile
    container_name: sqlmap
volumes:
  sqli-labs-apache2: {}
  sqli-labs-mysql: {}
  opt_splunk_etc:
  opt_splunk_var: